name: 'Tweet CfP'

on:
  issues:
    types: ['opened']

jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    env:
      CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
      ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Tweet 
        uses: snow-actions/tweet@v1.2.0
        with:
          status: |
            Ôºè
            Êñ∞„Åó„ÅÑCfP„ÅåÁôªÈå≤„Åï„Çå„Åæ„Åó„ÅüÔºÅÔºÅü¶Ñ
            „Çø„Ç§„Éà„É´Ôºö${{ github.event.issue.title }}
            Ôºº

            #AWSStartup
            ${{ github.event.issue.html_url }}